### ISSUE TITLE
create new logo

### ISSUE THREAD

**Issue by ripoul** [ripoul/georide-position#35]
For now I use my profile picture. I want a new one. It can be based on the [georide's one](https://georide.fr/wp-content/uploads/2019/05/logo_transparent_blanc-1-40px.png).

**Comment by Airthee** [comment]
@ripoul I'm on ! :boom:

**Comment by ripoul** [comment]
thx !

Le ven. 25 oct. 2019 à 20:33, Raphaël TISON <notifications@github.com> a
écrit :

**Comment by Airthee** [comment]
I did 2 different logos : simple and full.
What do you think ?
Full logo : 
![logo_full](https://user-images.githubusercontent.com/13355624/67602734-8f5e4680-f777-11e9-899c-f7feb22b0486.png)

Simple logo :
![logo_simple](https://user-images.githubusercontent.com/13355624/67602736-8f5e4680-f777-11e9-9218-58f033f153ff.png)

**Comment by ripoul** [comment]
the second one ! can u make it a png and make a pr pls ?
